---
all:
  vars:
    ansible_connection: ssh
    ansible_user: rahulc
    deployment_strategy: serial
    ansible_ssh_host_key_checking: false
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: true

    ## Required var, with options plaintext, ssl, sasl_ssl, ssl_customcerts, kerberos_ssl, kerberos, kerberos_ssl_customcerts
    security_mode: plaintext

    ## Required vars for any kerberos install
    # kerberos:
    #   realm: confluent.example.com
    #   kdc_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    #   admin_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    #   keytab_source_dir: <path to your keytabs, ex. /root/keytabs/, note the / at the end is mandatory>

    ## Required vars for customcerts install
    # ssl_ca_certificate: <ca certificate name, eg. ca-cert>
    # ssl_host_key: <host certificate name, eg. cert-signed>
    # ssl_private_key: <private key file name, must be pkcs format, eg. keystore.p12>
    # ssl_ca_certificate_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/ca-cert>
    # ssl_host_key_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/cert-signed>
    # ssl_private_key_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/keystore.p12>
    # host_keystore_storepass: <desired password fore each key-store>
    # host_truststore_storepass: <desired password for each trust-store>
    # ca_cert_password: <password for the ca certificate>
    # host_cert_password: <password for the host certificate>
    # privatekey_keystore_password: <password for the private key key-store (pkcs12 file)>

    ## To set custom properties for each service
    ## Find property options in the Confluent Documentation
    # zookeeper:
    #   properties:
    #     initLimit: 6
    #     syncLimit: 3
    # kafka_broker:
    #   properties:
    #     num.io.threads: 15
    # schema_registry:
    #   properties:
    #     key: val
    # control_center:
    #   properties:
    #     key: val
    # kafka_connect:
    #   properties:
    #     key: val
    # kafka_rest:
    #   properties:
    #     key: val
    # ksql:
    #   properties:
    #     key: val

zookeeper:
  hosts:
    35.227.173.91:
      ## By default the first host will get zookeeper id=1, second gets id=2. Set zookeeper_id to customize
      zookeeper_id: 1
    34.83.223.75:
      ## By default the first host will get zookeeper id=1, second gets id=2. Set zookeeper_id to customize
      zookeeper_id: 2
    34.168.69.63:
      ## By default the first host will get zookeeper id=1, second gets id=2. Set zookeeper_id to customize
      zookeeper_id: 3
